- name: install
  apt: pkg=dnsmasq

- name: dnsmasq dev config
  lineinfile: dest=/etc/dnsmasq.conf line='address=/dev/127.0.0.1'

- name: dnsmasq test config
  lineinfile: dest=/etc/dnsmasq.conf line='address=/test/127.0.0.1'

- name: dnsmasq address config
  lineinfile: dest=/etc/dnsmasq.conf line='listen-address=127.0.0.1'
